import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mjKedanty = localFont({
  src: [
    {
      path: "../public/fonts/MJ Kedanty.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/MJ Kedanty-Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-mj-kedanty",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mjKedanty.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
